### ISSUE TITLE
What to put in ***Should Ignore EOF*** argument?

### ISSUE THREAD

**Issue by dblairchappell** [yshavit/antlr-denter#25]
Hi there

This may be a really dumb question, so I apologise before asking it. 

In the below function definition, where it says "***Should Ignore EOF***", what should I do with this? Compiling the .g4 file with it as it is generates a syntax error. But if I remove that argument I get a "missing 1 required positional argument" error when calling the parser. 

I'm obviously misunderstanding something, so what is going on here? Any help would be greatly appreciated

Many thanks.
David

```
def nextToken(self):
    if not self.denter:
        self.denter = self.MyCoolDenter(self, self.NL, MyCoolParser.INDENT, MyCoolParser.DEDENT, ***Should Ignore EOF***)
    return self.denter.next_token()
```

**Comment by dblairchappell** [comment]
It's ok, I figured it out. I just put "True" instead of "Should Ignore EOF" in the .g4 file. See I told you it was a dumb question.  🤦‍♂️

**Comment by yshavit** [comment]
Yup, that's it! It's just a boolean field, which is similar to this boolean-returning method in Java's [`DenterOptions`](https://github.com/yshavit/antlr-denter/blob/main/Java/core/src/main/java/com/yuvalshavit/antlr4/DenterOptions.java).

I'm closing this ticket now, since it looks like you're all set. If you have any other questions, please feel free to re-open.

Not a stupid question, btw. :) It's a bit of a subtle aspect of the denter!
